# -*- coding: utf-8 -*-
"""(8 kyu) Short Long Short

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s_scmCgWz-3KRHwm2s0pGzyrTc5Sk5O2

Given 2 strings, a and b, return a string of the form short+long+short, with the shorter string on the outside and the longer string on the inside. The strings will not be the same length, but they may be empty ( length 0 ).

For example:

solution("1", "22") # returns "1221"

solution("22", "1") # returns "1221"
"""

def solution(a, b):
    if len(a) > len(b):
        return b + a + b
    else:
        return a + b + a