# -*- coding: utf-8 -*-
"""(6 kyu)-Array.diff

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ylzWoGJLUBawbA2yVqPXvLNQayZN312c

Your goal in this kata is to implement a difference function, which subtracts one list from another and returns the result.

It should remove all values from list a, which are present in list b.

array_diff([1,2],[1]) == [2]

If a value is present in b, all of its occurrences must be removed from the other:

array_diff([1,2,2,2,3],[2]) == [1,3]
"""

def array_diff(a, b):
    #your code here
    new_list = []
    for x in a:
        if x not in b:
            new_list.append(x)
        
    item_list = new_list
    return item_list