# -*- coding: utf-8 -*-
"""(6 kyu) Title Case

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18NZDUUkXOfs903xx9MeOJCJO9Smr-DET

A string is considered to be in title case if each word in the string is either (a) capitalised (that is, only the first letter of the word is in upper case) or (b) considered to be an exception and put entirely into lower case unless it is the first word, which is always capitalised.

Write a function that will convert a string into title case, given an optional list of exceptions (minor words). The list of minor words will be given as a string with each word separated by a space. Your function should ignore the case of the minor words string -- it should behave in the same way even if the case of the minor word string is changed.

###Arguments (Haskell)

> First argument: space-delimited list of minor words that must always be lowercase except for the first word in the string.


> Second argument: the original string to be converted.


###Arguments (Other languages)

> First argument (required): the original string to be converted.
> Second argument (optional): space-delimited list of minor words that must always be lowercase except for the first word in the string. The JavaScript/CoffeeScript tests will pass undefined when this argument is unused.
###Example

  

> title_case('a clash of KINGS', 'a an the of') # should return: 'A Clash of Kings'
  title_case('THE WIND IN THE WILLOWS', 'The In') # should return: 'The Wind in the Willows'
title_case('the quick brown fox') # should return: 'The Quick Brown Fox'
"""

def title_case(title, minor_words=''):
    palavras = minor_words.title()
    palavras = palavras.split()
    correct_title = []  
    title = title.title()
    
    for word in title.split():
        for i in range(1,len(correct_title)+1):
            if  word in palavras:
                word = word.casefold() 
        correct_title.append(word)  
        
    correct_title = " ".join(correct_title)
    
    return correct_title