# -*- coding: utf-8 -*-
"""(6 kyu)-Multiples of 3 or 5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LuC6OXPrrl4eS34gzhYVkI-zQRJ6qSJx

If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

Finish the solution so that it returns the sum of all the multiples of 3 or 5 below the number passed in.

Note: If the number is a multiple of both 3 and 5, only count it once. Also, if a number is negative, return 0(for languages that do have them)

Courtesy of projecteuler.net
"""

def solution(number):
      # Create empty list 
        thisList = []
        resList = list(range(1 , number))
        
        for x in resList:
            if x % 5 == 0 or x % 3 == 0:
                thisList.append(x)
                
        soma_lista = sum(thisList)
        return soma_lista