# -*- coding: utf-8 -*-
"""(7 kyu) Friend or Foe.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19sOPCyJIj8RrIvha_j7Qn_iAyFe2dBFM

Make a program that filters a list of strings and returns a list with only your friends name in it.

If a name has exactly 4 letters in it, you can be sure that it has to be a friend of yours! Otherwise, you can be sure he's not...

Ex: Input = ["Ryan", "Kieran", "Jason", "Yous"], Output = ["Ryan", "Yous"]

i.e.

friend ["Ryan", "Kieran", "Mark"] `shouldBe` ["Ryan", "Mark"]
Note: keep the original order of the names in the output.
"""

def friend(x):
    #Code
    a = str
    friend = []
    for a in x:
        if len(a) == 4:
            friend.append(a)
        
        
    return friend