# -*- coding: utf-8 -*-
"""(8 kyu) Opposite number

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X80KhYv8wpbuQ3XgKn-v9jHuKYX4mG_n

Very simple, given a number, find its opposite.

Examples:

1: -1

14: -14

-34: 34
"""

def opposite(number):
    opposite = -number
    return opposite