# -*- coding: utf-8 -*-
"""(8 kyu) Grasshopper - Variable Assignment Debug / Multiply

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GxG6jacFL0FJTKCBzRQwCo_EWxGpEyui

#**Variable assignment**

Fix the variables assigments so that this code stores the string 'devLab' in the variable **name**.
"""

a = "dev"
b = "Lab"

name = a + b

"""# Multiple

This code does not execute properly. Try to figure out why.
"""

def multiply(a, b):
  return a * b