# -*- coding: utf-8 -*-
"""(8 kyu Grasshopper) - Messi Goals

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GmZxJGG8Y1wY2rQfNejJB73eKfAj6HH5

Messi's Goal Total
Use variables to find the sum of the goals Messi scored in 3 competitions

Information
Messi goal scoring statistics:

Competition	Goals

La Liga =	43

Champions League = 10

Copa del Rey	= 5

Task

Create these three variables and store the appropriate values using the table above:

la_liga_goals

champions_league_goals

copa_del_rey_goals

Create a fourth variable named total_goals that stores the sum of all of Messi's goals for this year.
"""

la_liga_goals = 43
champions_league_goals = 10
copa_del_rey_goals = 5

total_goals = (la_liga_goals + champions_league_goals + copa_del_rey_goals)