# -*- coding: utf-8 -*-
"""(8 kyu) Convert boolean values to strings 'Yes' or 'No'.

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mB_L6WdC05jHa4vMsBwT4zS2_F7bYYdr

Complete the method that takes a boolean value and return a "Yes" string for true, or a "No" string for false.
"""

def bool_to_word(boolean):
    # TODO
    if boolean == True:
        bool_to_word = "Yes"
    if boolean == False:
        bool_to_word = "No"
        
    return bool_to_word