# -*- coding: utf-8 -*-
"""(8 kyu)Grasshopper - Summation

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ij7mFzYxUASaJMIkVtg_IH82HXN2RqjK

Write a program that finds the summation of every number from 1 to num. The number will always be a positive integer greater than 0.

For example:

summation(2) -> 3

1 + 2

summation(8) -> 36

1 + 2 + 3 + 4 + 5 + 6 + 7 + 8
"""

def summation(num):
    #criação das listas vazias
    listA = []
    thisList = []
    #condição para criação da lista inicial
    listA = list(range(1,num + 1))
    for x in listA:
        thisList.append(x)

    soma_lista = sum(thisList)

    return soma_lista