# -*- coding: utf-8 -*-
"""8 kyu - Grasshopper .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pE_xN8ZAstb3sVLFxg_7rC1TD2VLyMdf

Grade book
Complete the function so that it finds the mean of the three scores passed to it and returns the letter value associated with that grade.

Numerical Score	Letter Grade
90 <= score <= 100	'A'
80 <= score < 90	'B'
70 <= score < 80	'C'
60 <= score < 70	'D'
0 <= score < 60	'F'

Tested values are all between 0 and 100. Theres is no need to check for negative values or values greater than 100.

# Nova seção
"""

def get_grade(s1, s2, s3):
    # Code here
    list = (s1, s2 , s3)
    
    soma_das_notas = sum(list)    
    qtd_de_notas = len(list)
    media_das_notas = soma_das_notas / qtd_de_notas
    
    if media_das_notas > 90:
        return "A"
    if media_das_notas >= 80 and media_das_notas < 90 :
        return "B"
    if media_das_notas >= 70 and media_das_notas <80:
        return "C"
    if media_das_notas >= 60 and media_das_notas < 70:
        return "D"
        
    else:
        return "F"
