# -*- coding: utf-8 -*-
"""(8 kyu) Quarter of the year

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Sntauf5wqHoQFyIZr4XB9feMQU4z_R3A

Given a month as an integer from 1 to 12, return to which quarter of the year it belongs as an integer number.

For example: month 2 (February), is part of the first quarter; month 6 (June), is part of the second quarter; and month 11 (November), is part of the fourth quarter.
"""

def quarter_of(month):
    # your code here
    list1 = [1,2,3]
    list2 = [4,5,6]
    list3 = [7,8,9]
    list4 = [10,11,12]
    if month in list1:
        return 1
    if month in list2:
        return 2
    if month in list3:
        return 3
    else:
        return 4