# -*- coding: utf-8 -*-
"""(8 kyu) You Can't Code Under Pressure #1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vnNQ-w3gfZor-t5Zsd8h3zuHeXZsZUPm

Code as fast as you can! You need to double the integer and return it.
"""

def double_integer(i):
    # Double the integer and return it!
    double_number = 2*i
    return double_number