# -*- coding: utf-8 -*-
"""(8 kyu) Pre-FizzBuzz Workout #1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18LYD6kgnPzhd5N74RT5IE5kzaf-n1SfH

This is the first step to understanding FizzBuzz.

Your inputs: a positive integer, n, greater than or equal to one. n is provided, you have NO CONTROL over its value.

Your expected output is an array of positive integers from 1 to n (inclusive).

Your job is to write an algorithm that gets you from the input to the output.
"""

def pre_fizz(n):
    #your code here
    newArray = []
    for x in range(1,n+1):
        newArray.append(x)
    return newArray

