# -*- coding: utf-8 -*-
"""(8 kyu) Beginner - Lost Without a Map

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kBlVarG4PNdlXg8EA1HF2MyNpHiDzuvD

Given an array of integers, return a new array with each value doubled.

For example:

[1, 2, 3] --> [2, 4, 6]

For the beginner, try to use the map method - it comes in very handy quite a lot so is a good one to know.
"""

def maps(a):
    #setting the new list
    newArray = []
    #condition of the list: new array with each value doubled
    for x in a:
        newArray.append(2*x)
    
    return newArray