# -*- coding: utf-8 -*-
"""(8 kyu) Reversed Words

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MJxHS0GyslK4ImX7eCu1A9d8etyCjVjF

Complete the solution so that it reverses all of the words within the string passed in.

Example:

reverseWords("The greatest victory is that which requires no battle")

// should return "battle no requires which that is victory greatest The"
"""

def reverse_words(s):
    words = s.split(' ')
    words = reversed(words)
    words = " ".join(words)
    
    return words