# -*- coding: utf-8 -*-
"""(8 kyu) Sum of positive.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mIDfLaG6NVuGUfopF_mSNNP3AG3QziKY

You get an array of numbers, return the sum of all of the positives ones.

Example [1,-4,7,12] => 1 + 7 + 12 = 20

Note: if there is nothing to sum, the sum is default to 0.
"""

def positive_sum(arr):
    # Your code here
    max_sum = 0
    for num in arr:
        if num > 0:
            max_sum += num
                
    return max_sum