# -*- coding: utf-8 -*-
"""(8 kyu) Function 3 - multiplying two numbers

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T9wUBwIzvsADQpS6kSvCeDYft5UWVmnv

Implement a function which multiplies two numbers.
"""

def multiply(a,b):
#your code here
    result = a*b
    return result