# -*- coding: utf-8 -*-
"""(8 kyu) Beginner - Reduce but Grow

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IrqEwAKP0WsqDtLopeSJdCFwnUHq5mtA

Given a non-empty array of integers, return the result of multiplying the values together in order. Example:

[1, 2, 3, 4] => 1 * 2 * 3 * 4 = 24
"""

def grow(arr):
    number = 1
    for x in arr:
        number = number * x
        
    return number