# -*- coding: utf-8 -*-
"""(8_kyu)Reversed Strings.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zzon0SppLdiiVztUv2JId7GJo28NE_U0

Complete the solution so that it reverses the string passed into it.

'world'  =>  'dlrow'
"""

def solution(string):
    
    newString = string[::-1]
    
    return newString